# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from serial.tools import list_ports
from resources import logo


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #puertos detectados
        self.ports = {p[0]:p[0] for i,p in enumerate(list_ports.comports())}

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("background-color: rgb(23, 31, 50);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setStyleSheet("color:rgb(110,209,255);\n"
"background-color: rgb(0, 0, 21);\n"
"font: 14pt \"Fixed [Misc]\";")
        self.plainTextEdit.setTabChangesFocus(True)
        self.plainTextEdit.setDocumentTitle("")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Parity_label = QtWidgets.QLabel(self.centralwidget)
        self.Parity_label.setStyleSheet("color: rgb(39, 191, 12);\n"
"font: 63 14pt \"LMRomanDemi10\";")
        self.Parity_label.setObjectName("Parity_label")
        self.gridLayout.addWidget(self.Parity_label, 0, 3, 1, 1)
        self.rtscts_label = QtWidgets.QLabel(self.centralwidget)
        self.rtscts_label.setStyleSheet("color: rgb(39, 191, 12);\n"
"font: 63 14pt \"LMRomanDemi10\";")
        self.rtscts_label.setObjectName("rtscts_label")
        self.gridLayout.addWidget(self.rtscts_label, 2, 1, 1, 1)
        self.SelectStopbits = QtWidgets.QComboBox(self.centralwidget)
        self.SelectStopbits.setStyleSheet("color: rgb(207, 33, 255);\n"
"font: 63 12pt \"LMRomanDemi10\"")
        self.SelectStopbits.setObjectName("SelectStopbits")
        self.SelectStopbits.addItem("")
        self.SelectStopbits.addItem("")
        self.SelectStopbits.addItem("")
        self.gridLayout.addWidget(self.SelectStopbits, 1, 2, 1, 1)
        self.SelectTimeout = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SelectTimeout.setStyleSheet("background-color: rgb(27, 28, 45);\n"
"color: rgb(207, 33, 255);\n"
"font: 63 12pt \"LMRomanDemi10\"")
        self.SelectTimeout.setDecimals(3)
        self.SelectTimeout.setMaximum(10000.0)
        self.SelectTimeout.setObjectName("SelectTimeout")
        self.gridLayout.addWidget(self.SelectTimeout, 1, 4, 1, 1)
        self.EnRTSCTS = QtWidgets.QCheckBox(self.centralwidget)
        self.EnRTSCTS.setStyleSheet("\n"
"color: rgb(207, 33, 255);\n"
"font: 63 12pt \"LMRomanDemi10\"")
        self.EnRTSCTS.setObjectName("EnRTSCTS")
        self.gridLayout.addWidget(self.EnRTSCTS, 3, 1, 1, 1)
        self.SelectParity = QtWidgets.QComboBox(self.centralwidget)
        self.SelectParity.setStyleSheet("color: rgb(207, 33, 255);\n"
"font: 63 12pt \"LMRomanDemi10\"")
        self.SelectParity.setEditable(False)
        self.SelectParity.setObjectName("SelectParity")
        self.SelectParity.addItem("")
        self.SelectParity.addItem("")
        self.SelectParity.addItem("")
        self.SelectParity.addItem("")
        self.SelectParity.addItem("")
        self.SelectParity.addItem("")
        self.gridLayout.addWidget(self.SelectParity, 1, 3, 1, 1)
        self.SelectBITS = QtWidgets.QComboBox(self.centralwidget)
        self.SelectBITS.setStyleSheet("\n"
"color: rgb(207, 33, 255);\n"
"font: 63 12pt \"LMRomanDemi10\"")
        self.SelectBITS.setObjectName("SelectBITS")
        self.SelectBITS.addItem("")
        self.SelectBITS.addItem("")
        self.SelectBITS.addItem("")
        self.SelectBITS.addItem("")
        self.gridLayout.addWidget(self.SelectBITS, 1, 1, 1, 1)
        self.Stopbits_label = QtWidgets.QLabel(self.centralwidget)
        self.Stopbits_label.setStyleSheet("color: rgb(39, 191, 12);\n"
"font: 63 14pt \"LMRomanDemi10\";")
        self.Stopbits_label.setObjectName("Stopbits_label")
        self.gridLayout.addWidget(self.Stopbits_label, 0, 2, 1, 1)
        self.SelectPort = QtWidgets.QComboBox(self.centralwidget)
        self.SelectPort.setStyleSheet("color: rgb(207, 33, 255);\n"
"font: 63 12pt \"LMRomanDemi10\"")
        self.SelectPort.setObjectName("SelectPort")
        for cont in self.ports:
            self.SelectPort.addItem("")
        self.gridLayout.addWidget(self.SelectPort, 1, 0, 1, 1)
        self.Baudrate_label = QtWidgets.QLabel(self.centralwidget)
        self.Baudrate_label.setStyleSheet("color: rgb(39, 191, 12);\n"
"font: 63 14pt \"LMRomanDemi10\";")
        self.Baudrate_label.setObjectName("Baudrate_label")
        self.gridLayout.addWidget(self.Baudrate_label, 2, 0, 1, 1)
        self.xonxoff_label = QtWidgets.QLabel(self.centralwidget)
        self.xonxoff_label.setStyleSheet("color: rgb(39, 191, 12);\n"
"font: 63 14pt \"LMRomanDemi10\";")
        self.xonxoff_label.setObjectName("xonxoff_label")
        self.gridLayout.addWidget(self.xonxoff_label, 2, 3, 1, 1)
        self.SelectBaudrate = QtWidgets.QSpinBox(self.centralwidget)
        self.SelectBaudrate.setStyleSheet("background-color: rgb(27, 28, 45);\n"
"color: rgb(207, 33, 255);\n"
"font: 63 12pt \"LMRomanDemi10\"")
        self.SelectBaudrate.setMaximum(1000000)
        self.SelectBaudrate.setProperty("value", 9600)
        self.SelectBaudrate.setObjectName("SelectBaudrate")
        self.gridLayout.addWidget(self.SelectBaudrate, 3, 0, 1, 1)
        self.EnDSRDTR = QtWidgets.QCheckBox(self.centralwidget)
        self.EnDSRDTR.setStyleSheet("color: rgb(207, 33, 255);\n"
"font: 63 12pt \"LMRomanDemi10\"")
        self.EnDSRDTR.setObjectName("EnDSRDTR")
        self.gridLayout.addWidget(self.EnDSRDTR, 3, 2, 1, 1)
        self.BITS_label = QtWidgets.QLabel(self.centralwidget)
        self.BITS_label.setStyleSheet("color: rgb(39, 191, 12);\n"
"font: 63 14pt \"LMRomanDemi10\";")
        self.BITS_label.setObjectName("BITS_label")
        self.gridLayout.addWidget(self.BITS_label, 0, 1, 1, 1)
        self.EnXonXoff = QtWidgets.QCheckBox(self.centralwidget)
        self.EnXonXoff.setStyleSheet("color: rgb(207, 33, 255);\n"
"font: 63 12pt \"LMRomanDemi10\"")
        self.EnXonXoff.setObjectName("EnXonXoff")
        self.gridLayout.addWidget(self.EnXonXoff, 3, 3, 1, 1)
        self.Puerto_label = QtWidgets.QLabel(self.centralwidget)
        self.Puerto_label.setStyleSheet("color: rgb(39, 191, 12);\n"
"font: 63 14pt \"LMRomanDemi10\";")
        self.Puerto_label.setObjectName("Puerto_label")
        self.gridLayout.addWidget(self.Puerto_label, 0, 0, 1, 1)
        self.Timeout_label = QtWidgets.QLabel(self.centralwidget)
        self.Timeout_label.setStyleSheet("color: rgb(39, 191, 12);\n"
"font: 63 14pt \"LMRomanDemi10\";")
        self.Timeout_label.setObjectName("Timeout_label")
        self.gridLayout.addWidget(self.Timeout_label, 0, 4, 1, 1)
        self.DSRDTR_label = QtWidgets.QLabel(self.centralwidget)
        self.DSRDTR_label.setStyleSheet("color: rgb(39, 191, 12);\n"
"font: 63 14pt \"LMRomanDemi10\";")
        self.DSRDTR_label.setObjectName("DSRDTR_label")
        self.gridLayout.addWidget(self.DSRDTR_label, 2, 2, 1, 1)
        self.Start_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Stop.setStyleSheet("color: rgb(255, 90, 25);\n"
"font: 63 16pt \"LMRomanDemi10\"")
        self.Start_Stop.setObjectName("Start_Stop")
        self.gridLayout.addWidget(self.Start_Stop, 3, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.SelectParity.setCurrentIndex(0)
        self.SelectBITS.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pySerialMonitor"))
        MainWindow.setWindowIcon(QtGui.QIcon(":logo/igun.png"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Welcome to SerialMonitorG 1.0 (SMG_1.0)\n"
""))
        self.Parity_label.setText(_translate("MainWindow", "Parity"))
        self.rtscts_label.setText(_translate("MainWindow", "RTSCTS"))
        self.SelectStopbits.setItemText(0, _translate("MainWindow", "ONE"))
        self.SelectStopbits.setItemText(1, _translate("MainWindow", "ONE POINT FIVE"))
        self.SelectStopbits.setItemText(2, _translate("MainWindow", "TWO"))
        self.EnRTSCTS.setText(_translate("MainWindow", "Enable"))
        self.SelectParity.setItemText(0, _translate("MainWindow", "None"))
        self.SelectParity.setItemText(1, _translate("MainWindow", "Even"))
        self.SelectParity.setItemText(2, _translate("MainWindow", "Mark"))
        self.SelectParity.setItemText(3, _translate("MainWindow", "Names"))
        self.SelectParity.setItemText(4, _translate("MainWindow", "ODD"))
        self.SelectParity.setItemText(5, _translate("MainWindow", "Space"))
        self.SelectBITS.setCurrentText(_translate("MainWindow", "EIGHTBITS"))
        self.SelectBITS.setItemText(0, _translate("MainWindow", "FIVEBITS"))
        self.SelectBITS.setItemText(1, _translate("MainWindow", "SIXBITS"))
        self.SelectBITS.setItemText(2, _translate("MainWindow", "SEVENBITS"))
        self.SelectBITS.setItemText(3, _translate("MainWindow", "EIGHTBITS"))
        self.Stopbits_label.setText(_translate("MainWindow", "Stop bits"))
        self.Baudrate_label.setText(_translate("MainWindow", "Baudrate"))
        self.xonxoff_label.setText(_translate("MainWindow", "xonxoff"))
        self.EnDSRDTR.setText(_translate("MainWindow", "Enable"))
        self.BITS_label.setText(_translate("MainWindow", "Select bits"))
        self.EnXonXoff.setText(_translate("MainWindow", "Enable"))
        self.Puerto_label.setText(_translate("MainWindow", "Select Port"))
        self.Timeout_label.setText(_translate("MainWindow", "Time out"))
        self.DSRDTR_label.setText(_translate("MainWindow", "DSRDTR"))
        self.Start_Stop.setText(_translate("MainWindow", "Start"))

        self.i=0
        for key in self.ports.keys():
            self.SelectPort.setItemText(self.i,_translate("MainWindow",key))
            self.i+=1


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
